### PR TITLE
[1pt] PR: Added features to aggregate_outputs.py

### PR DESCRIPTION
**Pull request by BrianAvant-NOAA**
Adding features to `aggregate_outputs.py` to resolve issue #295 and issue #294

## Additions

- reprojecting grids to Web Mercator
- parallelize HUC6 aggregation
- changing grid blocksize from 256 to 1024 for faster postprocessing

## Note
This feature branch is derived from `dev-catfim-workflow` so it needs to be merged in after PR #292

### CODE REVIEW

**Comment by BradfordBates-NOAA** [comment]
@BrianAvant-NOAA It looks like this branch has conflicts with dev. Could you please merge and then I'll review

**Comment by BradfordBates-NOAA** [comment]
After the last patch, this branch is behind dev. Can you please merge again

**Comment by BrianAvant-NOAA** [comment]
merged

**Comment by BradfordBates-NOAA** [comment]
@BrianAvant-NOAA, a couple questions:

- Is there any change in usage in `fim_run.sh`? Any extra args?
- Is there any change to the metrics after projecting grids to Web Mercator?

**Comment by BrianAvant-NOAA** [comment]
@BradfordBates-NOAA 

- you can check the changes in the `Files changed` section; I set the jobs arg for `aggregate_fim_outputs.py` to 4 with no user access because we need to optimize on the API. We can do that later.
- metrics are run on the HUC8s currently. Web Mercator is used to reproject the HUC6s Viz use.

**Review by BradfordBates-NOAA — APPROVED** [review]

**Pull request merged**
