### PR TITLE
Dev levee

### PR DESCRIPTION
**Pull request by RyanSpies-NOAA**
### Goal: Incorporating the USACE National Levee Database levee elevation data into the hydrofabric

Documentation of feature enhancement: https://docs.google.com/document/d/1nJX6va_-GR6mDtQCZ4LuUbaFs8xu-sBpqM00ogY-0Zk/edit?usp=sharing

Description of feature enhancement
Problem:
The catchment boundaries defined in the HAND/FIM workflow often do not coincide with the levee centerline. By not representing the levee features in the hydofabric (DEM), HAND delineated catchments may not be defined by the levee features. This can lead to false positives in the modeled inundation. This can be especially important in urbanized areas. 
Screenshot 2020-10-01 100240

Solution
Levee data source → USACE National Levee Database (NLD)
Using the survey elevation data from the NLD, we can modify the 10-meter DEM to represent the levee features. Features include levee centerlines (embankments), flood walls, and closure structures. The NLD data is downloaded for each HUC2. The multiline features are filtered for missing elevation and erroneous data using a python preprocessing script. 

run_by_unit.sh modification:

- Added NLD clip to snap_and_clip_to_nhd.py
- Added gdal_rasterize function to rasterize all NLD polylines using zelev vertices
- Added gdal_calc function to burn nld levees into dem (& convert nld elev to meters)
- Added second gdal_calc function for thalweg negative burn value process (uses levee-burned dem if levees are present)

Computation metrics
Average computation time metrics (new functions in dev-levee) from running single HUCs with ~98% CPU allocation

- Clip NLD to WBD8 -> 1 second
- Rasterize all NLD polylines using zelev vertices -> 2 seconds
- Burn nld levees into dem (convert nld to meters) -> 8-10 seconds

Skill/impact enhancements
There are a limited number of BLE 1D HUCs that contain levee features. For the handful of leveed HUCS that do contain BLE data, it is unclear whether the BLE data is explicitly accounting for levee features or if the levee features are overtopped in the BLE model. Therefore, skill metrics were computed for the three evaluation HUCs, but the evaluation relied heavily on a qualitative evaluation. The following screenshots show the raster comparison images for three different HUC8 basins used for qualitative evaluation.

- 11010004 -> Middle White (floodwall and centerlines)
- 11110104 -> Robert S. Kerr Reservoir (floodwall and centerlines)
- 11110202 -> Dardanelle Reservoir (floodwall and centerlines)
Screenshot 2020-10-01 100842
Screenshot 2020-10-01 100856
Screenshot 2020-10-01 100907
Screenshot 2020-10-01 100918
Screenshot 2020-10-01 100934

Due to the limitations with the BLE inundation, the evaluation team will be modifying the eval codebase to exclude/mask the levee protected area polygons (excluded from the raster comparison calculations) within the run_test_case.py workflow for future evaluation needs.

*See google doc for summary of skill metrics

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by BrianAvant-NOAA** [comment]
It looks like there is no change in inundated area for HUCs 11010004 and 11110104. Is this because the levee center line does not cross the stream segment and therefore does not alter the catchment boundary?

**Comment by RyanSpies-NOAA** [comment]
There are two main reasons for the minimal inundation changes for those
HUCs.

   - Small-scale levees may be encircled by larger catchment → levee
   ignored in the final FIM
   - Blue lines bisecting levee features (no change in catchment
   delineation) → levee ignored in final FIM

[image: image.png]
[image: image.png]

**Review by BrianAvant-NOAA — APPROVED** [review]
I have reviewed this pull request by evaluating HUCs 11010004, 11110104, 11110202, 11130301, 11130302, 11130303, 11130304, 12090301, 12040101, and 12040103. HUCs with no levees show no change in evaluation metrics. CSI values for the three HUCs with levees agree with values posted in the pull request.
image
Although there is slight regression in CSI in two of the HUCs with levees, this feature branch provides a more realistic FIM in these areas which may or may not be incorporated into the BLE that is used in evaluation. We should update our evaluation process to exclude these areas from scoring going forward.

Manual inspection of 11110202 shows inundation extent matches dev branch except the leveed area. Below shows the 100yr inundation extent for dev/dev-levee at the levee:

image


When evaluating this feature branch I found a bug in run_by_unit where the hydroTable.csv was populated incorrectly on a HUC6 scale ('HUC' column contains NaNs). Running on a HUC8 scale did not cause this issue. I have confirmed that the issue exists on the dev branch as well. I have added dtype checks to add_crosswalk.py in the dev-levelpath-filter branch that should resolve this bug and I will check to see if it resolves the issue.

**Comment by RyanSpies-NOAA** [comment]
** Final squash-merge commit message @nickchadwick-noaa 

Incorporating levee elevation data into the DEM
-USACE National Levee Database data has been preprocessed for all CONUS HUC2s
-Rasterizing levee polylines
-Burning the elevation data into the DEM
-This change results in new catchment delineations that coincide with the levee lines
-Does not resolve all levee features (e.g. blue lines bisecting levee lines)

**Pull request merged**
