### PR TITLE
[3pt] PR: dev_eval_plots

### PR DESCRIPTION
**Pull request by TrevorGrout-NOAA**
Functionality to produce aggregated statistics and plots. An example would be:
python3 /path/to/eval_plots.py -m /path/to/metrics.csv -w /path/to/workspace -v fim_1 fim_2 fim_3_0_4_4 -f -sp /path/to/spatial/file.txt

Additionally, to run this feature branch a new docker image was created (dev_eval_plots).  Be sure to use this docker image when running feature branch.

Feature branch was run on the above command and example metrics are:

USGS_MS (decimals were truncated for readability)
version | magnitude | TP_area_km2 | FP_area_km2 | FN_area_km2 | csi | far | pod
-- | -- | -- | -- | -- | -- | -- | --
fim_1_0_0 | action | 112.03 | 141.16 | 67.32 | 0.350 | 0.558 | 0.625
fim_1_0_0 | major | 271.32 | 48.18 | 315.69 | 0.427 | 0.151 | 0.462
fim_1_0_0 | minor | 152.54 | 145.86 | 108.91 | 0.375 | 0.489 | 0.583
fim_1_0_0 | moderate | 243.08 | 87.51 | 257.45 | 0.413 | 0.265 | 0.486
fim_2_x_ms | action | 120.65 | 78.97 | 58.57 | 0.467 | 0.396 | 0.673
fim_2_x_ms | major | 307.50 | 30.90 | 276.50 | 0.500 | 0.091 | 0.527
fim_2_x_ms | minor | 171.61 | 101.43 | 88.96 | 0.474 | 0.371 | 0.659
fim_2_x_ms | moderate | 268.56 | 58.79 | 229.95 | 0.482 | 0.180 | 0.539
fim_3_0_4_4_ms_c | action | 128.87 | 118.86 | 33.28 | 0.459 | 0.480 | 0.795
fim_3_0_4_4_ms_c | major | 342.22 | 52.01 | 133.76 | 0.648 | 0.132 | 0.719
fim_3_0_4_4_ms_c | minor | 182.27 | 130.71 | 50.22 | 0.502 | 0.418 | 0.784
fim_3_0_4_4_ms_c | moderate | 285.64 | 91.73 | 106.46 | 0.590 | 0.243 | 0.728

NWS MS (decimals were truncated for readability)
version | magnitude | TP_area_km2 | FP_area_km2 | FN_area_km2 | csi | far | pod
-- | -- | -- | -- | -- | -- | -- | --
fim_1_0_0 | action | 259.78 | 223.06 | 204.30 | 0.378 | 0.462 | 0.560
fim_1_0_0 | major | 567.40 | 158.37 | 524.01 | 0.454 | 0.218 | 0.520
fim_1_0_0 | minor | 390.01 | 282.59 | 330.23 | 0.389 | 0.420 | 0.542
fim_1_0_0 | moderate | 514.45 | 219.44 | 477.37 | 0.425 | 0.299 | 0.519
fim_2_x_ms | action | 290.77 | 192.04 | 172.02 | 0.444 | 0.398 | 0.628
fim_2_x_ms | major | 703.66 | 106.84 | 381.95 | 0.590 | 0.132 | 0.648
fim_2_x_ms | minor | 457.10 | 207.18 | 260.70 | 0.494 | 0.312 | 0.637
fim_2_x_ms | moderate | 613.70 | 152.90 | 373.48 | 0.538 | 0.199 | 0.622
fim_3_0_4_4_ms_c | action | 312.45 | 264.51 | 148.81 | 0.431 | 0.458 | 0.677
fim_3_0_4_4_ms_c | major | 741.12 | 162.71 | 341.17 | 0.595 | 0.180 | 0.685
fim_3_0_4_4_ms_c | minor | 481.93 | 296.74 | 234.81 | 0.476 | 0.381 | 0.672
fim_3_0_4_4_ms_c | moderate | 653.31 | 231.46 | 332.22 | 0.537 | 0.262 | 0.663

### CODE REVIEW

**Comment by BradfordBates-NOAA** [comment]
This is awesome! Here are some minor items to add.

- [ ] All filenames changed to "snake_case"
- [ ] Add "extent" label to any plot (FR/MS)
- [ ] Only write scatterplots if user supplies two explicit version names
- [ ] Remove "Target/Baseline Better" annotations
- [ ] In subset CSVs, change "_data" to "_analyzed_data"

Again, this is awesome!

**Comment by TrevorGrout-NOAA** [comment]
Brad,
I have updated the feature to include your items. I also added configuration to all filenames. See sample pictures below:
image
image
image

**Comment by BradfordBates-NOAA** [comment]
Should have added this to my previous comment:

- [ ] Change the "MR" and "FR" directories to "mr" and "fr" 
image

**Review by BradfordBates-NOAA — APPROVED** [review]

**Comment by TrevorGrout-NOAA** [comment]
Updated the configuration subfolders to be lower case.

image

**Review by BradfordBates-NOAA — APPROVED** [review]

**Pull request merged**
