### PR TITLE
Mannings's n calibration feature

### PR DESCRIPTION
**Pull request by BrianAvant-NOAA**
This feature branch adds Manning's n calibration capabilities to FIM 3. Issue #10 

## Additions

1. mannings_calibration_run.sh
    * inputs:
        * fimdir - fim output directory with completed run_by_unit.sh files
        * huclist - list of HUCs to calibrate
        * outdir - output directory for mannings parameter adjustment files
        * paramfile - csv with Manning's parameter sets by row (stream orders 1-14)

2. time_and_tee_mannings_calibration.sh
    * initiates parallelized run of `mannings_run_by_set.sh`. currently no log

3. mannings_run_by_set.sh
for each parameter set for a single HUC this script calls:
    * `add_crosswalk.py` to update the hydrotable and saves in the `outdir `.
    * `run_test_case_calibration.py` is a modified version of `run_test_case.py` (these two files will be merged with task #81). It uses the new hydrotable path to calculate statistics for a given Manning's n value.
    * creates a nested file structure: test_cases/<huc8>_ble/performance_archive/development_versions/mannings_calibration/$strorder/$mannings_value

example call:
```/foss_fim/tests/mannings_calibration_run.sh -d dev_faf2237_huc8 -t /data/temp/parameter_adj_files/dev_fim_ble.lst -g /data/temp/mannings_calibration_dev_faf2237_huc8 -n data/temp/parameter_adj_files/param_adj_mannings.csv -j 6```

Note: the current configuration can parallelize parameter sets for each HUC in the huclist, but will iterate through each HUC one at a time.

4.  aggregate_mannings_calibration.py 
A post processing script that collects stats for all HUCs and Manning's n value combinations and saves them to a collective summary file (mannings_calibration_summary_dev_faf2237_huc8_full.csv) and aggregate scores by stream order file (aggregate_metrics_mannings_calibration_by_streamorder.csv). It also generates a json file with the optimal Manning's n parameter set.
    * inputs:
        * huc_list_path - list of HUCs to aggregate
        * calibration_stat_folder - eval stat column name
        * summary_file - output file with aggregate Manning's calibration stats

example call:
```python3 /foss_fim/tests/aggregate_mannings_calibration.py -l /data/temp/parameter_adj_files/dev_fim_ble.lst -c mannings_calibration_dev_faf2237_huc8_200 -f /data/temp/optimal_mannings_dev_faf2237_huc8/mannings_calibration_summary_dev_faf2237_huc8_full.csv```

currently you need to manually rerun the optimal parameter set but this could be automated once we get the API set up on the production machines

## Changes
- updates add_crosswalk.py with calibration mode arguments
- addresses path bug in all_ble_stats_comparison.py

## Methods
48 HUC8s were used in this analysis to assess the sensitivity of Manning's n on inundation extents for the 100yr and 500yr flood events. Manning's n was varied by stream order (1-10) using a range of 0.03 to 0.125 in 0.05 increments. Because we are not routing flow, it is assumed that segments do not influence the inundation of others and therefore stream orders can be evaluated independently. 

Of the 48 HUC8s, the highest stream order ranged from 6-10:
stream order 6 -> 100% HUCs
stream order 7 -> 98% of HUCs
stream order 8 -> 75% of HUCs
stream order 9 -> 27% of HUCs
stream order 10 -> 13% of HUCs

## Calibration Results
Sensitivity of Manning's n decreases with stream order. For all sensitive stream orders, CSI scores improve with higher Manning's n values. (showing 100yr event)

Mannings_single_plot

Stream orders 1-7 achieve the highest CSI scores at the upper bound, suggesting that additional improvement in CSI may be gained by increasing the range of Manning's n. The upper bound used in this study is still below some of the the maximum reference values shown below. Going forward, we may want to increase the upper bound of Manning's n to 0.16 to see if the model improves.

image
image

Relationship between CSI and Manning's n by stream order - individual HUC8s (showing 100yr event)
Mannings_by_streamorder_individual

Relationship between CSI and Manning's n by stream order - aggregate of all 48 HUC8s (showing 100yr event)
Mannings_by_streamorder_aggregate

## Testing
FIM 3 (dev_faf2237) CSI comparison 
- 100yr
image
image

- 500yr
image
image

FIM 2.3.3 CSI Comparison
- 100yr
image

- 500yr
image

- Aggregate scores for 48 BLE HUC8s
image

## Subset test 
To test this script without running the entire list of parameter sets you can do the following:
1. edit  mannings_run_by_set.sh line 15 -> `python3 foss_fim/tests/run_test_case_calibration.py -r $fimdir/$huc -d $subdir -t $huc"_ble" -b "mannings_calibration"/$strorder/$mannings_value`
    * change "mannings_calibration" to "mannings_calibration_test" so it doesn't overwrite the current dev calibration outputs
2. Create a subset of `data/temp/parameter_adj_files/param_adj_mannings.csv`
    * each row is a parameter set so you can test with fewer rows
    * example row=[1,1,0.03,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06] where row[0] = iteration, row[1] = stream order, row[2] = mannings n for SO 1, ... row[-1] = mannings n for SO 14
3. Use shorter huclist

As a guide a single run (one HUC, one parameter set) takes about 2 minutes. 
Total run time ~ # HUCs x # parameter sets x 2 minutes / # jobs
I have found that due to memory constraints, the maximum number of jobs you can run on the VM for this tool is currently 6

### CODE REVIEW

**Comment by BradfordBates-NOAA** [comment]
Recommend updating -t flag in mannings_calibration_run.sh to accept a single HUC in quotes, or update flag description to minimize user error.

**Comment by BradfordBates-NOAA** [comment]
I followed the testing instructions and was able to run the process with no errors. I will approve this Pull Request, but I recommend revisiting these scripts on a future sprint to seek opportunities to merge divergent scripts to allow for more script polymorphism.

**Review by BradfordBates-NOAA — APPROVED** [review]
Recommend in future sprints to merge divergent scripts with polymorphism functionality by adding additional flags.

**Comment by BradfordBates-NOAA** [comment]
After a conversation for the second review, I suggest allowing users to define the location of the calibrated manning's json file. This could be a flag. If the user does not define a location, then the flag could default to the repo location.

**Review by BradfordBates-NOAA — APPROVED** [review]
I ran the test again and supplied a single HUC for the -t argument. I also tried this test with the HUCs in quotes. And I tried passing multiple HUCs in quotes divided by a space--this also worked.

**Comment by AndyCarter-NOAA** [comment]
2021.04.29 - After review, I am concerned that there is a weakness in this analysis.  The problem is that the Manning's 'n' is a assigned based on a CSI performance on the comparison to BLE models for the 100yr (and maybe the 500 year) events only.  There is likely a severe overestimation of the Manning's on the lower stream orders and specifically around the main channel conveyance.  As such, there is too much friction resistance in the low flows of the channel.

**Comment by BrianAvant-NOAA** [comment]
@AndyCarter-NOAA I agree. At the time this was created, we only had BLE data to compare to. We have delayed any further calibration of Manning's n so that we can improve FIM 3 bathymetry and rating curves, but we will need to revisit this soon. @RyanSpies-NOAA recently ran some scenarios varying Manning's n with the latest FIM to show CSI scores for the CatFIM thresholds. Ryan can you share that slide deck?

**Pull request merged**
