### PR TITLE
[8pt] PR: Correct headwater assignment nws_lid layer

### PR DESCRIPTION
**Pull request by TrevorGrout-NOAA**
The nws_lid layer is_headwater field incorrectly attributed if an ahps location was immediately downstream of an actual headwater point.  This has been corrected and it appears to affect 35 of 4,000+ sites. This addresses issue #383 and issue #397.

## Changes

- Fix incorrect classification of headwater status for some sites in the nws_lid.gpkg layer.

## Testing

1. run the "generate_nws_lid.py" script

## Screenshots
LCAT2 is not assigned as a headwater (red dots)
image
WOBT2 not assigned as a headwater (red dots)
image
EMIU1 is correctly assigned as headwater (red dots) and RBCU1, RBRU1, CCSU1 are correctly classified as not_headwaters.
image

### CODE REVIEW

**Comment by TrevorGrout-NOAA** [comment]
I will need to update the changelog to account for the correct version/date when PRs in front of this one get merged in. I will also have to update the feature branch when the PR in front of this one gets approved.

**Comment by BrianAvant-NOAA** [comment]
Adding #397 to this PR because I think we can address it as well.

**Comment by TrevorGrout-NOAA** [comment]
Aggregate metrics were computed and were identical:

USGS | Action | Minor | Moderate | Major
-- | -- | -- | -- | --
fim_3_0_16_1_ms_c | 0.430 | 0.455 | 0.509 | 0.556
nws-lid-hotfix_fim_run_ms_c | 0.430 | 0.455 | 0.509 | 0.556


NWS | Action | Minor | Moderate | Major
-- | -- | -- | -- | --
fim_3_0_16_1_ms_c | 0.454 | 0.489 | 0.546 | 0.613
nws-lid-hotfix_fim_run_ms_c | 0.454 | 0.489 | 0.546 | 0.613

**Comment by TrevorGrout-NOAA** [comment]
@BrianAvant-NOAA I synced this fb with dev and updated the changelog did you need to update anything in the code that would require a changelog edit?

**Comment by BrianAvant-NOAA** [comment]
@TrevorGrout-NOAA I swapped out the nhd input paths in the `fim_run.sh` and renamed them on the VM. Go ahead and update the changelog and I will approve. I am in the process of updating the NWM inputs now.

**Review by BrianAvant-NOAA — DISMISSED** [review]

**Comment by TrevorGrout-NOAA** [comment]
@BradfordBates-NOAA this has been approved

**Pull request merged**
