### PR TITLE
[1pt] PR: Added Probability Not Detected (PND) to evaluation code

### PR DESCRIPTION
**Pull request by BradfordBates-NOAA**
This merge adds Probability Not Detected (PND) as a metric to the evaluation code. It also updates an argument name in `eval_plots.py` after a matplotlib update.

### Changes

- `synthesize_test_cases.py`: added PND into the dictionary of searched metrics
- `tool_shared_variables.py`: added PND to the `GO_DOWN_STATS` list variable
- `tools_shared_functions.py`: added the PND calculation and inclusion into `stats_dictionary`
- `eval_plots.py`:  added automatic plotting of PND and inclusion in spatial outputs. Also updated an argument in matplotlib call (I changed `b` to `visible`) in accordance with matplotlib recommendations concerning an impending deprecation of `b`.

### Testing
To test, you can open `/test_cases/metrics_library/all_official_versions.csv` and confirm that the `PND` is present.

You can also run `eval_plots.py` and confirm that the `PND` metrics are included in the plot and spatial outputs. Or you could look at my outputs in `/temp/brad/pnd_workspace2`.

Here's an example of the PND box and whisker plot: 
image

### CODE REVIEW

**Comment by RyanSpies-NOAA** [comment]
Just to confirm: TPR = POD. Looks like we use `TPR` in the code but I think we've also used POD when discussing this enhancement. Just want to check that they are represent the same thing.

**Comment by BradfordBates-NOAA** [comment]
That's correct; TPR = POD, so 1-TPR = PND.

**Comment by RyanSpies-NOAA** [comment]
Approved. This will be a nice eval addition.

- Confirmed `PND` is present in `/test_cases/metrics_library/all_official_versions.csv`
- Checked TPR and PND equations
- Checked PND plots from `eval_plots.py`

**Review by RyanSpies-NOAA — APPROVED** [review]
Approve approved

**Pull request merged**
