### PR TITLE
[3pt] PR: Dev Catfim spatial

### PR DESCRIPTION
**Pull request by TrevorGrout-NOAA**
Update to 3.0.10.0 to implement a few additional features and stability fixes.

Updated fixes to handle WRDS API output (with recent updates that were implemented).
Renamed scripts to better describe what they do (generate_categorical_fim_flows.py and generate_categorical_fim_mapping.py).
Added a wrapper script (generate_categorical_fim.py) that links the "flows.py" and "mapping.py" scripts.
Updated the status outputs of the nws_lid layer and saved it in the same directory as the merged catfim layer.
Additional minor stability fixes.

There are a couple residual bugs that need to be sorted out that appear to affect some sites (see issues #317 & #318).  Total runtime is quite lengthy and should be run overnight. An example run is as follows:

python3  generate_categorical_fim.py -f fim_3_0_9_0_ms_c -j 13

Will the reviewer please examine the output shapefiles in the "mapping" directory.  The nws_lid_sites shapefile has a "mapped" field and a "status" field. The "mapped" field indicates whether a site contains mapping in the catfim_library shapefile. If not, then the "status" field explains why:
Missing nwm segments --> No segments associated with site.
Missing threshold stages --> No stages supplied with site.
Missing calculated flows --> Stages were supplied but flows not available (e.g. exceeded rating curve).

If any site only has some thresholds that have flow files created then those are noted. The number of sites indicated as having mapping in the nws_lid_sites match the sites listed in the merged CatFIM spatial layer.  **The status field does NOT have information related to geometries are in the CatFIM spatial layer but may not be valid.**

This feature branch resolves tickets #305, #321, #322

### CODE REVIEW

**Comment by BradfordBates-NOAA** [comment]
All in all, this looks good. Here are some comments:

- [ ] Sync `mapped` column with `viz` column (a join should do this)
- [ ] Ensure no more than 2 significant digits in `q` and `stage` fields
- [ ] Confirm lower case `yes` and `no` in `viz` and `mapped` fields

**Comment by TrevorGrout-NOAA** [comment]
@BradfordBates-NOAA 

These should be linked as-is. The "viz" column is appropriately populated as "yes" for all records in the catfim_library.shp. If a threshold does not have spatial data it would not be in the catfim_library.shp.  The nws_lid_sites.shp layer lists all sites, and gives explanation for why a site may not be included in the catfim_library.shp. But all sites in the nws_lid_sites.shp that are designated as having mapping are also found in the catfim_library.shp. This was manually verified.

The catfim_library.shp file has no more than 2 decimal places  for "q" and "stage" attribute fields when viewed in ArcMap.  Can you describe where you saw the behavior you mention?

All "Yes","No" were converted to lower case

**Comment by BradfordBates-NOAA** [comment]
Okay thanks for confirming the fields are synced and for changing to lowercase. Here's a screenshot of the catfim_library's attribute table, showing the significant digits in Q. Maybe it's just a Q thing?

image

**Comment by TrevorGrout-NOAA** [comment]
This may be a difference between QGIS and ArcMap:
image

**Comment by TrevorGrout-NOAA** [comment]
One last commit to ensure column naming consistency between catfim_library.shp and nws_lid_sites.shp

**Comment by BradfordBates-NOAA** [comment]
@TrevorGrout-NOAA Please merge with latest dev and then we can merge this in.

**Comment by TrevorGrout-NOAA** [comment]
@BradfordBates-NOAA I have updated this with recent changes to dev. Please advise what version of dev this will be and I will update changelog accordingly.

**Pull request merged**
