### PR TITLE
Dev alt hydrocond

### PR DESCRIPTION
**Pull request by TrevorGrout-NOAA**
Implement AGREE stream burn in method to create more realistic pixel catchments and ultimately mapping.

## Additions
Added the following scripts:  
r_distance_grow.py --> creates allocation and proximity grids using GRASS gis r.grow.distance tool. 
agreedem.py --> creates AGREE dem using methodology from F. Hellweger (https://www.caee.utexas.edu/prof/maidment/gishydro/ferdi/research/agree/agree.html)
modified run_by_unit.sh --> added calls to run agreedem.py
modified /config/params_template.env --> added buffer parameter (set to default 70).
This feature branch requires GRASS be installed in docker image
## Removals
modified run_by_unit.sh --> remove ## BURN NEGATIVE ELEVATIONS STREAMS ## step.

## Changes
Implementing AGREE hydroconditioning method brings FIM 3 more in line with FIM 2 methods. The AGREE DEM methodology is documented by Ferdi Hellweger (https://www.caee.utexas.edu/prof/maidment/gishydro/ferdi/research/agree/agree.html). Two new scripts were written to perform the AGREE dem creation. One script (agreedem.py) performs the bulk of the steps related to AGREE dem creation, the other script (r_grow_distance.py) is a function that specifically runs GRASS gis r.grow.distance. A flag was enabled in the agreedem.py that deletes all intermediate datasets once the final AGREE dem is created. There are three adjustable parameters in the AGREE process, smooth drop, sharp drop, and stream buffer. For this PR a simple sensitivity analysis was performed on the stream buffer parameter.  Currently, FIM 2 uses a default stream buffer of 5 cells (50m) and for FIM 3 a buffer of 7 cells (70m) was determined to be optimal for the evaluated hucs.  
## Testing
A total of 48 HUC 08 watersheds were evaluated and CSI scores were compiled. When compared to current dev (faf2237) the CSI improved with an average % change of +2.27% and +1.98% for the 100 year and 500 year maps respectively for the 70m buffer.  In an effort to maximize the performance across all HUC locations, the 70m buffer appeared to offer a good compromise between maximizing the minimal % improvement for both the 100 and 500 year events as well as the average and maximum % improvement.  It is readily admitted that a user may justify another buffer width and to help make that adjustment trivial, the "buffer" parameter was exposed in the /config/params_template.env file.  Currently, the buffer variable is a global assignment (all streams buffered same amount).  

**Table 1: 100 Year % Change in CSI for varying buffer widths**
  | Statistic | 50m | 60m | 70m | 80m | 90m
-- | -- | -- | -- | -- | -- | --
  | Max | 9.62% | 10.55% | 11.30% | 11.86% | 12.41%
  | Average | 1.62% | 1.93% | 2.27% | 2.58% | 2.79%
  | Min | -0.73% | -0.03% | 0.19% | 0.12% | -0.36%
dev_faf2237_huc8 100yr CSI | site | 50m | 60m | 70m | 80m | 90m
60.31% | 11090202 | 2.13% | 2.65% | 2.69% | 3.17% | 3.63%
45.87% | 11090203 | 1.25% | 2.21% | 2.79% | 2.91% | 3.25%
56.47% | 11090204 | 0.47% | 0.50% | 0.60% | 0.76% | 0.59%
57.69% | 11100303 | 0.47% | 0.69% | 0.79% | 0.72% | 0.83%
54.59% | 11130302 | 6.96% | 8.05% | 9.05% | 9.91% | 10.64%
52.18% | 11130303 | 5.72% | 6.49% | 8.13% | 8.53% | 9.28%
56.78% | 11130304 | 1.89% | 2.50% | 3.04% | 3.40% | 4.01%
55.10% | 11130301 | 9.62% | 10.55% | 11.30% | 11.86% | 12.41%
58.43% | 12020001 | 1.36% | 1.69% | 2.15% | 2.42% | 2.70%
49.79% | 12020002 | 1.25% | 1.46% | 1.63% | 2.12% | 2.38%
54.74% | 12020003 | 1.26% | -0.03% | 0.45% | 1.23% | 0.79%
64.75% | 12020004 | 0.93% | 1.23% | 1.34% | 1.58% | 1.93%
57.20% | 12020005 | 1.53% | 1.92% | 2.34% | 2.74% | 3.09%
53.14% | 12020006 | 0.89% | 0.99% | 1.12% | 1.04% | 1.16%
39.31% | 12020007 | 0.05% | 0.20% | 0.31% | 0.55% | 0.63%
54.31% | 12030104 | 0.30% | 0.32% | 0.43% | 0.45% | 0.54%
55.00% | 12030107 | 1.50% | 1.70% | 1.85% | 2.02% | 2.20%
50.49% | 12030108 | 1.67% | 1.81% | 2.60% | 2.82% | 3.11%
49.87% | 12030109 | 1.02% | 1.11% | 1.25% | 1.58% | 1.90%
60.23% | 12040101 | 1.01% | 1.29% | 1.57% | 2.60% | 2.81%
56.06% | 12040103 | 0.14% | 0.21% | 0.53% | 0.60% | 0.83%
48.65% | 12060202 | 1.36% | 1.54% | 1.52% | 1.94% | 2.23%
57.56% | 12090301 | 0.30% | 0.34% | 0.41% | 0.80% | 0.81%
57.43% | 12100201 | 0.64% | 0.53% | 0.52% | 0.68% | 0.76%
63.46% | 12100202 | 0.59% | 0.73% | 0.77% | 0.83% | 0.98%
59.58% | 12100203 | 0.28% | 0.30% | 0.33% | 0.37% | 0.46%
34.66% | 13020101 | -0.73% | 0.53% | 0.39% | 0.51% | -0.36%
34.21% | 13020102 | 1.91% | 2.18% | 2.39% | 2.81% | 3.03%
62.06% | 11010004 | -0.09% | 0.33% | 0.37% | 0.12% | 0.09%
77.03% | 11010009 | 1.33% | 1.17% | 1.52% | 2.15% | 2.23%
53.36% | 11010014 | 0.47% | 0.57% | 0.96% | 1.61% | 1.32%
57.31% | 11110202 | 0.42% | 0.46% | 0.37% | 0.36% | 0.53%
58.05% | 11110205 | -0.29% | 0.12% | 0.19% | 0.15% | 0.00%
60.98% | 11050003 | 2.91% | 3.04% | 3.45% | 3.78% | 4.20%
50.33% | 11120303 | 1.19% | 1.39% | 1.32% | 1.21% | 1.15%
46.37% | 11130202 | 4.76% | 5.91% | 7.36% | 7.67% | 8.03%
47.68% | 11130203 | 4.04% | 4.77% | 5.65% | 6.40% | 6.83%
55.56% | 11130208 | 1.15% | 1.45% | 1.74% | 2.28% | 2.77%
61.55% | 11140102 | 2.16% | 2.82% | 3.17% | 3.49% | 3.97%
56.04% | 11140103 | 0.79% | 0.93% | 0.91% | 1.16% | 1.26%
60.13% | 11140104 | 6.83% | 7.71% | 9.35% | 10.99% | 12.09%
61.18% | 11110104 | 0.96% | 1.14% | 1.16% | 1.08% | 1.24%
52.77% | 11140105 | 1.65% | 1.83% | 2.11% | 2.48% | 2.70%
62.22% | 11070103 | 0.75% | 1.04% | 1.49% | 1.76% | 1.90%
53.18% | 8040101 | 0.38% | 0.47% | 0.56% | 0.59% | 0.61%
62.73% | 8040203 | 1.13% | 2.01% | 2.40% | 2.64% | 3.38%
39.16% | 12060102 | 1.16% | 1.44% | 1.67% | 2.13% | 2.22%
55.41% | 8070201 | 0.35% | 0.50% | 0.71% | 0.74% | 0.74%

**Table 2: 500 Year % Change in CSI for varying buffer widths**
  | Statistic | 50m | 60m | 70m | 80m | 90m
-- | -- | -- | -- | -- | -- | --
  | Max | 8.09% | 8.87% | 9.64% | 10.09% | 10.52%
  | Average | 1.45% | 1.72% | 1.98% | 2.25% | 2.41%
  | Min | -0.35% | -0.02% | -0.05% | -0.14% | -0.28%
dev_faf2237_huc8 500yr CSI | site | 50m | 60m | 70m | 80m | 90m
63.08% | 11090202 | 1.68% | 2.23% | 2.42% | 2.91% | 3.37%
49.06% | 11090203 | 1.22% | 2.04% | 2.48% | 2.55% | 2.90%
57.86% | 11090204 | 0.46% | 0.49% | 0.62% | 0.76% | 0.63%
60.46% | 11100303 | 0.65% | 0.85% | 0.94% | 0.98% | 1.02%
59.08% | 11130302 | 5.85% | 6.69% | 7.41% | 8.09% | 8.88%
57.12% | 11130303 | 4.91% | 5.45% | 6.88% | 7.12% | 7.57%
58.56% | 11130304 | 1.80% | 2.17% | 2.64% | 3.43% | 3.85%
59.38% | 11130301 | 8.09% | 8.87% | 9.64% | 10.09% | 10.52%
60.94% | 12020001 | 1.10% | 1.39% | 1.81% | 2.01% | 2.23%
52.63% | 12020002 | 0.90% | 1.07% | 1.27% | 1.58% | 1.85%
56.57% | 12020003 | 2.00% | 1.10% | 0.83% | 1.70% | 1.60%
67.21% | 12020004 | 0.74% | 0.92% | 1.00% | 1.24% | 1.57%
59.99% | 12020005 | 1.30% | 1.63% | 2.01% | 2.36% | 2.63%
55.30% | 12020006 | 0.49% | 0.59% | 0.69% | 0.70% | 0.73%
40.19% | 12020007 | 0.69% | 0.81% | 0.90% | 0.67% | 0.75%
57.06% | 12030104 | 0.29% | 0.29% | 0.30% | 0.33% | 0.39%
58.45% | 12030107 | 1.40% | 1.51% | 1.74% | 1.84% | 1.94%
55.00% | 12030108 | 1.39% | 1.55% | 2.05% | 2.23% | 2.45%
53.19% | 12030109 | 0.51% | 0.64% | 0.70% | 0.95% | 1.16%
62.27% | 12040101 | 1.12% | 1.52% | 1.89% | 2.61% | 2.71%
59.54% | 12040103 | 0.02% | 0.16% | 0.37% | 0.48% | 0.51%
52.25% | 12060202 | 1.00% | 1.04% | 1.03% | 1.48% | 1.87%
61.54% | 12090301 | 0.14% | 0.23% | 0.31% | 0.44% | 0.53%
62.45% | 12100201 | 0.44% | 0.36% | 0.42% | 0.61% | 0.69%
66.56% | 12100202 | 0.37% | 0.50% | 0.61% | 0.65% | 0.75%
63.26% | 12100203 | 0.21% | 0.25% | 0.27% | 0.30% | 0.40%
36.14% | 13020101 | 0.33% | 1.43% | 1.41% | 1.55% | 0.71%
36.05% | 13020102 | 2.78% | 3.08% | 3.21% | 3.65% | 3.76%
64.23% | 11010004 | -0.08% | 0.36% | 0.52% | 0.56% | 0.50%
80.37% | 11010009 | 1.03% | 0.92% | 1.02% | 1.41% | 1.35%
52.96% | 11010014 | 0.33% | 0.41% | 0.78% | 1.33% | 0.94%
58.91% | 11110202 | 0.59% | 0.62% | 0.50% | 0.49% | 0.65%
58.50% | 11110205 | -0.35% | -0.02% | -0.05% | -0.14% | -0.28%
63.22% | 11050003 | 2.44% | 2.59% | 2.90% | 3.31% | 3.76%
52.44% | 11120303 | 1.02% | 1.17% | 1.18% | 1.07% | 0.93%
50.85% | 11130202 | 4.29% | 5.50% | 6.54% | 6.97% | 7.54%
51.84% | 11130203 | 3.34% | 3.82% | 4.49% | 5.17% | 5.38%
60.81% | 11130208 | 0.81% | 0.93% | 1.04% | 1.44% | 1.84%
64.07% | 11140102 | 1.70% | 2.14% | 2.42% | 2.69% | 3.04%
57.45% | 11140103 | 0.64% | 0.72% | 0.71% | 0.91% | 0.96%
64.15% | 11140104 | 6.23% | 6.89% | 8.43% | 9.59% | 10.42%
63.42% | 11110104 | 0.80% | 0.98% | 1.00% | 0.93% | 1.02%
53.89% | 11140105 | 1.43% | 1.58% | 1.89% | 2.25% | 2.47%
62.01% | 11070103 | 0.71% | 0.90% | 1.32% | 1.57% | 1.62%
55.54% | 8040101 | 0.32% | 0.40% | 0.49% | 0.49% | 0.49%
63.16% | 8040203 | 1.09% | 1.92% | 2.30% | 2.58% | 3.23%
45.39% | 12060102 | 1.16% | 1.33% | 1.54% | 1.76% | 1.87%
55.71% | 8070201 | -0.01% | 0.65% | 0.00% | 0.14% | 0.03%

When looking at metrics aggregated across all sites, the improvement for the 100 year across 48 huc 08 watersheds, there is a overall improvement in CSI.

  | CSI
-- | --
dev_faf2237_100yr | 55.38%
FB_100yr | 56.54%

## Screenshots
HUC 11130303 contains a few excellent examples showing the benefit of incorporating an AGREE DEM. 

**Example 1: NHDPlusBurnLineEvent_subset: NHDPlusID = 21000300092604**

FIM 2 pixel catchment. Note where the catchment drains to the river.
image

Comparison of FIM 2 and FIM 3 pixel catchments. Note where drainage to river occurs.
image

The pixel catchment ultimately affects how the mapping aligns as it partially controls the reference elevation used for REM creation. Note the difference in mapping between FIM 2 (which uses AGREE) vs FIM 3 (steep channel burn in).
image

This image shows the mapping with FIM 3 which uses AGREE DEM.
image

For reference here is the FIM 3 (steep burn in) along with BLE mapping to see where benchmark is inundating.
image

Example 2: 11130303 NHDPlusBurnLineEvent_subset: NHDPlusID = 21000300092604

Pixel catchments for FIM 3 (steep burn in) note the extent of the catchment and where it drains to the river.
image

Pixel catchments for FIM 3 (AGREE), note how the large catchment has been split up and how drainage to the river has been altered.
image

Note output inundation from FIM 2 vs FIM 3 (steep burn in) vs FIM 3 AGREE.
image

As an aside, here is a comparison between differing buffer widths (50m vs 80m). Note how 80m added additional mapping.
image

Additional examples of areas in 11130303: GW catchment 335197 and 236337
In this example, note how incorporating the AGREE DEM altered the stream that the catchment drained to. As such, it better reflected the benchmark data.
image

In this example note how a large catchment was subdivided when using AGREE DEM.
image

## Notes
It would be appreciated if the reviewer would lend a 2nd set of eyes to ensure that the AGREE methodology was correctly followed as set forth by Hellweger.

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [ ] Windows
- [ ] Linux
- [ ] Browser

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by TrevorGrout-NOAA** [comment]
As a follow up, HUC 1110205 was the poorest performing HUC.   For this HUC, using a 70m buffer, a reduction of false positives by 0.3 km2 yields an improvement in CSI for the 500 year. Upon visual inspection, it was evident there were numerous areas of mapping extending beyond the extent of the benchmark streams. All predicted mapping upstream of the benchmark streams is recorded as a false positive. As the AGREE DEM generally increases predicted mapping, then these areas will result in more false positives. Github ticket #12 may help in addressing this issue.  


  | Dev_faf2237_100yr | FB_100yr | Dev_faf2237_500yr | FB_500yr
-- | -- | -- | -- | --
Predicted Wet (km2) | 229.4 | 238.66 | 249.72 | 258.79
CSI | 0.5805 | 0.5816 | 0.5850 | 0.5847

In this image for HUC 11110205 an example of mapping extending beyond benchmark:
image

**Comment by TrevorGrout-NOAA** [comment]
This addresses tickets: #25 and #78

**Comment by BradfordBates-NOAA** [comment]
Please go ahead and merge the dev branch into this feature branch so it is up to date with dev.

**Comment by BradfordBates-NOAA** [comment]
I noticed the "-d" (dem_cm) argument description in agreedem.py with the description "DEM raster in cm", however the script is called in run_by_unit.sh with the dem_meters.tif file

**Comment by BradfordBates-NOAA** [comment]
It would be great if we documented the hydrologic rationale for this step in run_by_unit.sh. Perhaps something like this:

## Create AGREE DEM ##
# The following step is required for X, Y, and Z reasons. 
# More notes here
# More notes here
echo ...........................

Also, the docstrings in agreedem.py and other new Python scripts are great, however I recommend that line length does not exceed 100 characters. For reference, pep8 recommends docstrings don't exceed 72 characters. This just makes it easier to follow along code without horizontal scrolling. A return can be included with another hash sign. For example, the docstring on line 95 would look like this.

    # 5. From Hellweger documentation: Compute the buffer distance grids (bufdist and bufallo). 
    # The cells in the buffer distance grid (bufdist) store the distance to the closest valued 
    # buffer grid cell (bufgrid2). The cells in buffer allocation grid (bufallo) store the 
    # elevation of the closest valued buffer cell.

**Comment by BradfordBates-NOAA** [comment]
Please comment on these warnings:

image

**Comment by BradfordBates-NOAA** [comment]
After temporarily removing the "-t" flag from the agreedem.py call in run_by_unit.sh, I ran fim_run.sh, stepped through agreedem.py and compared the intermediate outputs with the desired behavior described in Hellweger's documentation. I did this for 11130304. From my review, it appears that the intermediate outputs are correctly produced according to the documentation provided.

After my previous comments are addressed, I will approve this Pull Request.

**Comment by TrevorGrout-NOAA** [comment]
> I noticed the "-d" (dem_cm) argument description in agreedem.py with the description "DEM raster in cm", however the script is called in run_by_unit.sh with the dem_meters.tif file

Good catch, I fixed this to be "dem_m" and the description now reads "DEM raster in meters"

**Comment by TrevorGrout-NOAA** [comment]
> Please comment on these warnings:
> 
> image

Upon review a few experiments were conducted:
The AGREE process was modified to output 64 bit floats and the warning messages are indeed caused by the exported datatype of Float32. 
32bit messages
image

64bit messages 
image

The output statistics were identical for both the 32bit float vs 64 bit float

total_area | tsg_grass_warning_test_32float_100yr | tsg_grass_warning_test_64float_100yr | diff
-- | -- | -- | --
CSI | 0.613207507 | 0.613207507 | 0
TPR | 0.668391146 | 0.668391146 | 0
TNR | 0.990247005 | 0.990247005 | 0
FAR | 0.118662726 | 0.118662726 | 0
MCC | 0.746602856 | 0.746602856 | 0
TP_area_km2 | 173.0073 | 173.0073 | 0
FP_area_km2 | 23.2936 | 23.2936 | 0
TN_area_km2 | 2365.0599 | 2365.0599 | 0
FN_area_km2 | 85.8341 | 85.8341 | 0
contingency_tot_area_km2 | 2647.1949 | 2647.1949 | 0
TP_perc | 6.535495365 | 6.535495365 | 0
FP_perc | 0.87993521 | 0.87993521 | 0
TN_perc | 89.34211455 | 89.34211455 | 0
FN_perc | 3.242454872 | 3.242454872 | 0


total_area | tsg_grass_warning_test_32float_500yr | tsg_grass_warning_test_64float_500yr | diff
-- | -- | -- | --
CSI | 0.650990323 | 0.650990323 | 0
TPR | 0.708089736 | 0.708089736 | 0
TNR | 0.989265032 | 0.989265032 | 0
FAR | 0.110217978 | 0.110217978 | 0
MCC | 0.772131474 | 0.772131474 | 0
TP_area_km2 | 204.3969 | 204.3969 | 0
FP_area_km2 | 25.3188 | 25.3188 | 0
TN_area_km2 | 2333.2165 | 2333.2165 | 0
FN_area_km2 | 84.2627 | 84.2627 | 0
contingency_tot_area_km2 | 2647.1949 | 2647.1949 | 0
TP_perc | 7.721263742 | 7.721263742 | 0
FP_perc | 0.956438833 | 0.956438833 | 0
TN_perc | 88.1392035 | 88.1392035 | 0
FN_perc | 3.183093923 | 3.183093923 | 0

Furthermore, the contingency rasters for both FLOAT32/FLOAT64 were identical.

The allocation rasters for both FLOAT32 and FLOAT64 were compared and the difference was zero for both the bufgrid_allo and the smogrid_allo raster. There were differences found in the proximity grids between the FLOAT32 and FLOAT64 scenarios with differences generally on the order of 0.000XXXXm. This was consistent for both the bufgrid proximity and smogrid proximity rasters.  The output dem_burned.tif  (although both were FLOAT32) also had minor differences on the order  0.0000XXXXXm

As a final test, the r.grow.distance tool was manually run in GRASS on both FLOAT32 and FLOAT64 datasets and in both cases the the outputs from r.grow.distance were both DCELL or FLOAT64 datatype. It appears that r.grow.distance doesn't produce output of the same datatype as the input.  The input dem (dem_meters) to the AGREE step is a FLOAT32 datatype and this datatype is preserved throughout the process. The small differences in the proximity rasters (FLOAT32 vs FLOAT64) are inconsequential as the proximity raster is in meters.  For this application, it appears that the warning sign from the gdal export raster is ok to ignore.

**Comment by TrevorGrout-NOAA** [comment]
> After temporarily removing the "-t" flag from the agreedem.py call in run_by_unit.sh, I ran fim_run.sh, stepped through agreedem.py and compared the intermediate outputs with the desired behavior described in Hellweger's documentation. I did this for 11130304. From my review, it appears that the intermediate outputs are correctly produced according to the documentation provided.
> 
> After my previous comments are addressed, I will approve this Pull Request.

I have removed the -t flag at this time so that intermediate datasets remain. After further discussions there should be a janitor script that cleans up all intermediate data to reduce file sizes.

**Comment by TrevorGrout-NOAA** [comment]
> It would be great if we documented the hydrologic rationale for this step in run_by_unit.sh. Perhaps something like this:
> 
> ```
> # Create AGREE DEM # 
> # The following step is required for X, Y, and Z reasons. 
> # More notes here
> # More notes here
> # echo ...........................
> ```
> 
> Also, the docstrings in agreedem.py and other new Python scripts are great, however I recommend that line length does not exceed 100 characters. For reference, pep8 recommends docstrings don't exceed 72 characters. This just makes it easier to follow along code without horizontal scrolling. A return can be included with another hash sign. For example, the docstring on line 95 would look like this.
> 
> ```
> # 5. From Hellweger documentation: Compute the buffer distance grids (bufdist and bufallo). 
> # The cells in the buffer distance grid (bufdist) store the distance to the closest valued 
> # buffer grid cell (bufgrid2). The cells in buffer allocation grid (bufallo) store the 
> # elevation of the closest valued buffer cell.
> ```

I have made the prescribed changes. I feel that another lengthier document should be created detailing all the steps in fim_run.sh.

**Review by BradfordBates-NOAA — APPROVED** [review]
All of my comments have been addressed or explained. The warnings documented were proven to be inconsequential. Perhaps in the future we can find a way to suppress them, but for now I see no reason this branch should not be merged into dev. The demonstrated improvement is very exciting and should make a positive difference in our inundation mapping capability.

**Comment by TrevorGrout-NOAA** [comment]
This Pull Request addresses issues #25 and #78

**Pull request merged**
