### PR TITLE
[9pt] PR: Cahaba Codebase Cleanup - Small Items

### PR DESCRIPTION
**Pull request by nickchadwick-noaa**
The PR addresses issue #432 

All changes in this PR are to better clean up and organize the repo, as well as removing any unused scripts, packages, and code.

### CODE REVIEW

**Comment by nickchadwick-noaa** [comment]
Currently testing this PR using Docker image `foss-fim:dev-cleanup`. Will post any issues I find.

**Comment by BradfordBates-NOAA** [comment]
@nickchadwick-noaa Can you make sure this branch is up to date with dev? I see there a conflict in `run_test_case.py`, let me know if you need assistance resolving it.

**Comment by BradfordBates-NOAA** [comment]
@nickchadwick-noaa Please ensure the Changelog is updated

**Comment by BradfordBates-NOAA** [comment]
@nickchadwick-noaa Can you also do a full BED test using the API to confirm non-zero exit statuses in all HUCs?

**Review by BradfordBates-NOAA — APPROVED** [review]

**Pull request merged**
