### PR TITLE
[2pt] PR: adjust SRC with user observed feedback points

### PR DESCRIPTION
**Pull request by RyanSpies-NOAA**
This new workflow ingests FIM point observations from users and “corrects” the synthetic rating curves to produce the desired FIM extent at locations where feedback is available (locally calibrated FIM). This approach is similar to the "pin to flood" methodology but differs in that this workflow aims to adjust the entire rating curve. Addresses #436 and #450 

## Changes

- `add_crosswalk.py`: added 'NextDownID' and 'order_' attributes to the exported hydroTable.csv. This will potentially be used in future enhancements to extend SRC changes to upstream/downstream catchments.
- `adjust_rc_with_feedback.py`: added a new workflow to perform the SRC modifications (revised discharge) using the existing HAND geometry variables combined with the user provided point location flow and stage data.
- `inundation_wrapper_custom_flow.py`: updated code to allow for huc6 processing to generate custom inundation outputs. 

## Testing

- To date all testing and development has been performed on huc6 aggregated outputs for 120401, 120903, and 102701

## Screenshots
image
Example showing two data points of "observed" stage & flow plotted on the raw HAND-derived rating curve

image
Example of the original and revised FIM extents using the observation point data

## Notes

Code methodology for adjust_rc_with_feedback.py:

1. Loop and find the corresponding hydroids in the Hydrotable
2. Grab slope, wetted area, hydraulic radius, and feature_id that correspond with the matching hydroids and HAND value for the nearest stage
3. Calculate new column for new roughness using the above info
4. If multiple flows exist per hydroid, aggregate the resulting Manning Ns → use median. If range of resulting Manning Ns is high, notify human (put this in a log file?)
6. Update hydrotable.csv
7. Copy default flow and N columns to new columns with "_default" in the field name
8. Overwrite the official flow and N columns with the new calculated values
9.  Add last_updated column with timestamp where values were changed
10. Update JSON file
11. Update SRC for catchments that have the same feature_id
12. If these catchments already have known data, then let it use those. If not, use new calculated Ns.

## Next Steps

- Test and evaluate this workflow with additional (and larger) observation point data

### CODE REVIEW

**Review by BradfordBates-NOAA — APPROVED** [review]
Nice work!

**Comment by frsalas-noaa** [comment]
Does this commit define how far up and downstream the adjustment is applied or is that separate?

**Comment by RyanSpies-NOAA** [comment]
Currently, the modifications to the SRC's are restricted to the hydroid
catchments that contain user-provided calibration points. I then do a
second pass to apply the same adjustments (i.e. modified manning's n) to
any hydroids that share a featureid. In other words, the changes are
limited to the featureid catchment where we have observation points. We are
not applying changes upstream or downstream, but I have the routing
attributes readily available in the hydroTable if we decide to try that.

**Comment by frsalas-noaa** [comment]
Ok thanks. Please add a card in backlog to implement modification downstream. TBD on methodology for that but I understand some ideas have been discussed.

**Comment by RyanSpies-NOAA** [comment]
Follow-on card #463

**Pull request merged**
