### PR TITLE
[1pt] PR: Generate flow files for CatFIM

### PR DESCRIPTION
**Pull request by TrevorGrout-NOAA**
Addresses github #271 and github #274

Ability to generate flows for catfim. All external functions were placed in the "tools_shared_functions.py". This branch also utilizes .env files which contain sensitive paths/urls. This feature branch will search for all nws_lids in CONUS that have the attribute "rfc_forecast_point" as well as all nws_lids in HI/PR.  It intersects the nws_lid points with the FIM HUC 08 layer to create a directory of hucs and subdirectories of nws_lids. Within each subdirectory are subfolders of each threshold category (action, minor, moderate, major, and record) which are populated with flow files used for inundation mapping. Each flow file contains a list of NWM segments that are on the mainstem and a flow (in cms). Mainstem NWM segments are determined using a function using a multi-pass algorithm to get all NWM segments that are downstream of nws_lid sites. At the end of the script all info files are aggregated into a master info file which is placed in the parent workspace directory. An example call for this function is:

Currently it takes approximately 2.5 hours to run. This is quite slow compared to runtime of about 45 minutes on personal pc. To run the script you must checkout the "dev-catfim-flow" docker image as it contains additional required python packages.
`python3 generate_categorical_fim_flows.py -w /path/to/workspace -u 10 -d 10`

Some potential tickets that may need to be created:
There is some uncertainty on the CRS used by WRDS for the lat/lon locations. The script currently uses information that WRDS reports, however, an update may need to be implemented when CRS is sorted out with WRDS, especially if a new field is reported by WRDS.

Additionally, when writing the flow file, WRDS reports potentially two calculated flow sources: NRLDB and USGS. Currently, the USGS is given priority. It has been reported that for at least some sites (github #273 ), the NRLDB may be more accurate than the USGS. This may require a future enhancement.

Reasons why a site is not produced include:
It did not intersect with the FIM HUC 8 layer (outside the domain)
Outside the domain of the NWM (Alaska)
It does not have a name specified.
It does not have any flows specified for all thresholds.
No NWM segments

### CODE REVIEW

**Comment by BradfordBates-NOAA** [comment]
This branch is now behind dev. Please update before review.

**Comment by BrianAvant-NOAA** [comment]
@TrevorGrout-NOAA @BradfordBates-NOAA 

merged with FIM v3.0.8.2
updated `generate_categorical_fim.py`

Requested changes

- [ ] make sure that `nws_lid_attributes` table outputs HUC column as a string with leading zeroes
- [ ] run entire categorical fim process for `catfim_gaps_ms_c` outputs to test

**Comment by TrevorGrout-NOAA** [comment]
I have updated the feature branch with dev. I have updated the feature branch to not strip off leading zeros in file outputs. Output spatial files are being projected based on the USGS supplied projection (which is currently mis-reported by WRDS) and then reprojecting everything to WGS 84.

It takes a couple hours to run this so I am currently running it to make sure it I didn't break anything, but I also propose that instead of having the reviewer rerun the entire process in order to merge, if my run is successful then we use that as evidence and I can point the reviewer to the outputs. As far as review, the main thing would be to have an external eye maybe take one site and compare it to WRDS and verify correct flow is being passed to flow file for a couple thresholds?

@BrianAvant-NOAA WRDS currently mis-reports the lat/lon datum. I have been in discussions with the WRDS developers and they have implemented a fix that won't be pushed until tonight. I propose running the 'official' catfim flows this evening/weekend and then running the generate_categorical_fim.py on Monday morning. 

I feel that if someone does a quick look at the flow files being created and maybe look at spatial output (?) that should be sufficient to merge this feature branch. When WRDS updates their API we can run the final CatFIM this evening.

**Comment by TrevorGrout-NOAA** [comment]
@BradfordBates-NOAA @BrianAvant-NOAA 
Also, I do think a reviewer should at least start a run to make sure the .env file is working correctly, but not necessarily run the whole 2 hour process.

**Comment by BradfordBates-NOAA** [comment]
I can do a test run. Can you please make the output spatial projection Web Mercator? You can import the projection info from utils (`VIZ_PROJECTION`).

**Review by BradfordBates-NOAA — APPROVED** [review]

**Comment by BradfordBates-NOAA** [comment]
All in all, this looks really good. Here are a few comments:

- [ ] Ensure no more than 2 decimal places in `q` and `stage` fields in `catfim_library.shp`
- [ ] Sync the `mapped` column in `nws_lid_sites.shp` with the `viz` column in `catfim_library.shp` (a join should work here)
- [ ] In `nws_lid_sites.shp`, change values of `mapped` column to all lowercase, i.e. "yes", "no"

**Pull request merged**
