### PR TITLE
[1pt] PR: Tool to compare synthetic rating curve with benchmark rating curve (sierra test)

### PR DESCRIPTION
**Pull request by BrianAvant-NOAA**
Create tool to compare synthetic rating curve with benchmark rating curve (sierra test). resolves issue #293; resolves issue #308

## Additions

1. `usgs_gage_crosswalk.py`: generates `usgs_elev_table.csv` in run_by_unit.py with elevation and additional attributes at USGS gages. 

- Data columns: `['location_id','HydroID','dem_elevation','dem_adj_elevation','min_thal_elev', 'med_thal_elev','max_thal_elev','str_order']`

- USGS gage is moved to closest FIM stream segment using linear referencing and elevation data is collected at the adjusted point location.

2. `rating_curve_comparison.py`: post-processing script to plot and calculate metrics between synthetic rating curves and USGS rating curve data. 

- Metrics: NRMSE, mean_abs_y_diff, percent_bias

- Statistics are calculated at the 1.5, 5, and 10 year NWM recurrence interval as well as USGS observed flows. The `group` argument can be used to calculate statistics on a slice the data.

- example call:
`python3 /foss_fim/tools/rating_curve_comparison.py -output_dir 'data/outputs/dev-usgs-crosswalk_new_fr_c' -gages 'data/temp/tsg/usgs_rating_curve/usgs_rating_curves.csv' -flows '/data/inundation_review/inundation_nwm_recurr/nwm_recurr_flow_data' -j 14 -group 'recurr_interval'`

## Changes

- update `aggregate_fim_outputs.py` call argument in `fim_run.sh` from 4 jobs to 6 jobs (optimizing API performance)
- reroutes median elevation data from `add_crosswalk.py` and `rem.py` to new file (depreciating `hand_ref_elev_table.csv`)
- adding new files to `viz_whitelist` in `output_cleanup.py`

## Todos

- add function to get USGS rating curve data from WRDS API instead of csv

## Note
This feature branch will have no affect on the performance of FIM.

### CODE REVIEW

**Comment by TrevorGrout-NOAA** [comment]
I was able to verify that for the 1.5 year recurrance interval for HUC 01010003 (gage 01013500) that the correct nwm return flow was being used and that the correct elevations were interpolated for the recurrance flow (also verifying units). I also spot-checked the snapping of the USGS gage to the stream network and was able to replicate results from `usgs_elev_table.csv` (did not attempt to calculate median thalweg elevation).  I am getting some discrepancies with the statistics when I try to calculate by hand. I am currently getting a 2nd opinion to make sure my math is correct.

Otherwise some (mostly minor) things that may be helpful:

-Appear to be missing leading zeros for USGS gage sites. The leading zeros are present in the `usgs_elev_table` however they are not present in the `nwm_recurrence_flow_elevations.csv` and the `usgs_interpolated_elevation_stats.csv`

-Can we truncate elevations/flows to the nearest hundredth when creating csv files

-Possible to untether the output_dir argument from the fim_run output directory, maybe add another argument to place output?

-Can we add the NWM feature_id to the usgs_elev_table? This will make it a lot less hassle to walk through all the intermediate steps if we need to.

-How are the aggregate scores calculated? Are we averaging all the individual metrics from `usgs_interpolated_elevation_stats.csv` (NRMSE, Percent Bias, MAD), or are we calculating actual metrics but on a much large sample size? 

-Can we reference units wherever possible otherwise this may lead to some confusion ( `mean_abs_y_diff` to `mean_absolute_elev_diff_ft` , `elevation` to `elevation_<units>`).

-Make all columns lower case (`NRMSE` to `nrmse`)

-Multiple hucs in the `/data/outputs/dev-usgs-crosswalk_new_ms_c/` directory appear to have all of the fim_run output (like they crashed?)

-I think we could probably just produce the `FIM-USGS_rating_curve_comparison.png` plot as it appears to be the original input data (lets consult with Ryan on this). The legend appears to be quite a distance from the actual plot. If this is time consuming, we can tackle this on another feature branch. I wonder if we can use consistent snake case in the plot name.


Nice job! This is going to be a huge help in assessing rating curves. If you have questions please reach out.

**Comment by TrevorGrout-NOAA** [comment]
I am running this command:
`python3 /foss_fim/tools/rating_curve_comparison.py -fim_dir /data/outputs/dev-usgs-crosswalk_PR_ms_c -output_dir /data/temp/tsg/ba_review -gages /data/temp/tsg/usgs_rating_curve/usgs_rating_curves.csv -flows /data/inundation_review/inundation_nwm_recurr/nwm_recurr_flow_data -group 'recurr_interval' -j 6`

And I am getting this message:
```
Traceback (most recent call last):
  File "/foss_fim/tools/rating_curve_comparison.py", line 371, in <module>
    log_file = open(join(output_dir,'rating_curve_comparison.log'),"w")
FileNotFoundError: [Errno 2] No such file or directory: '/data/temp/tsg/ba_review/rating_curve_comparison.log'
```

**Comment by BrianAvant-NOAA** [comment]
@TrevorGrout-NOAA I just ran the same command with no issue. Maybe check your permissions?

**Comment by TrevorGrout-NOAA** [comment]
I am able to get this to run. 

I am still having issues replicating statistics and I would like to replicate at least one site manually. For example in HUC 02040105, location ID 01446500, we have the following metrics:


location_id | feature_id | recurr_interval | discharge_cfs | HUC | HUC4 | str_order | source | elevation_ft
-- | -- | -- | -- | -- | -- | -- | -- | --
1446500 | 2588381 | 1.5 | 32519.19 | 2040105 | 204 | 6 | USGS | 236.06
1446500 | 2588381 | 5 | 63891.71 | 2040105 | 204 | 6 | USGS | 240.07
1446500 | 2588381 | 10 | 93429.28 | 2040105 | 204 | 6 | USGS | 243.1
1446500 | 2588381 | 1.5 | 32519.19 | 2040105 | 204 | 6 | FIM | 259.57
1446500 | 2588381 | 5 | 63891.71 | 2040105 | 204 | 6 | FIM | 267.72
1446500 | 2588381 | 10 | 93429.28 | 2040105 | 204 | 6 | FIM | 273.98

I am manually getting the following metrics:
nrmse = 3.91, mean_absolute_difference_ft = 27.35, Percent Bias = 11.41

Here is what is reported:

location_id | nrmse | mean_abs_y_diff_ft | percent_bias
-- | -- | -- | --
1446500 | 1.054508 | 0.009878 | 13.19304

**Comment by TrevorGrout-NOAA** [comment]
After running the latest commit, I was able to successfully run and replicate statistics for HUC 02040105 Site 01446500 and manually replicated the output stats.  I also verified the aggregate scores for the 1.5 year return interval. The suggested edits were incorporated. This is pretty impressive. Good Job!

New stats are shown:

location_id | nrmse | mean_abs_y_diff_ft | percent_bias
-- | -- | -- | --
1446500 | 3.908029 | 27.34667 | 11.40664

**Review by TrevorGrout-NOAA — DISMISSED** [review]
Approved.

**Comment by TrevorGrout-NOAA** [comment]
@BrianAvant-NOAA Please make sure this feature branch is fully up to date with dev prior to the merge.

**Comment by TrevorGrout-NOAA** [comment]
@BrianAvant-NOAA Make sure to update the changelog also.

**Review by TrevorGrout-NOAA — APPROVED** [review]

**Pull request merged**
