### PR TITLE
Updating logging and fixing bug in vector preprocessing

### PR DESCRIPTION
**Pull request by BrianAvant-NOAA**
Updating logging and fixing bug in vector preprocessing. Resolves issue #416. Resolves issue #427.

## Additions

- `fim_completion_check.py` adds message to docker log to log any HUCs that were requested but did not finish `run_by_unit.sh`

- adding `input_data_edits_changelog.txt` to the inputs folder to track any manual or version/location specific changes that were made to data used in FIM 3. Most of the code will be in the repo but this will help locate it if we upgrade datasets.

## Changes

- fixed bug in `reduce_nhd_stream_density.py` where non-nested HUC8s were not populating attributes correctly.
- fixed bug in `mprof plot` call
- providing unique exit codes to relevant domain checkpoints within `run_by_unit.sh`
- updating input folder `ahp_sites` to `ahps_sites`
- improved error handling in `add_crosswalk.py`
- remove single node segments in `split_flows.py`
- fixed HUC specific errors (10030203, and 16050103)

**MS remaining missing HUC8s**

- HUC 10030203: has something to do with WBD boundary and TauDEM flow direction/accumulation. It will require some time to pinpoint the exact issue but it looks like the NHDPlus HR has a break in the network.
  image

  Further inspection of this site shows that there is a breach in the NHDPlus HR network at Tiber Dam:
  image
  The two highlighted segments have the same `FromNode` attribute value but the difference in `LevelPathI` and `DnLevelPat` values guide the traversal downstream to the left (right highlighted segment in image) where the reach is terminated with a `DnLevelPat` value of 0. I have rerouted the segments using the `LevelPathI` and `DnLevelPat` attributes without changing the geometry.

  Update: Manually removed segment to produce catchments
  image

- HUC 16050103: NWS LID NIXN2 is not labeled as a headwater site. Updating this should fix this HUC. (I have manually updated this layer but will need to rerun the aggregate preprocessing script to see the results)
  image

  Updated catchments
  image

- HUC 10170104: no NHDPlus HR data for this HUC (I have manually removed this HUC from the MS list)
  image

**FR Failed/missing HUC8s**

There were no missing HUC8s for FR.

Failed FR HUCs

- HUC 04140102: The error in `run_by_unit.sh` is related to a missing `order_` attribute when trying to replace the rating curves of short streams. The HUC includes the boundary of a Great Lake but otherwise seems normal. I will investigate this HUC further to get more information. UPDATE: added a line to `split_flows.py` to remove segments that share the same `From_Node` and `To_Node` value. Not sure why this occurs but is the only case in the entire NWM domain.

- HUC 04240001: Island within Lake Huron; There is a mismatch between NWM stream segments and NHDPlus HR segments in this area. (I have manually removed this HUC from the FR list)
  image
  Where the green lines are NHDPlus HR and the blue lines are NWM. Maybe this area is still under revision. I have removed this layer from the FR HUC list `included_huc8.lst`. 

- HUC 09020311: The error in `run_by_unit.sh` is related to a missing `order_` attribute when trying to replace the rating curves of short stream segments and has been resolved with this PR. A visual inspection shows there some other things going on though. NWM only has stream segments on the US side of the border which is around 50% of the HUC area. Currently we don't have a method for filtering out those areas that are within the HUC boundary but not represented by the NWM domain. Those FIM derived catchemnts/streams will crosswalk to NWM stream IDs that are outside of the catchment boundaries. I still recommend that we accept this error for FIM3. Many changes are coming with the NWM network as well as improved resolutions in the input data so any changes related to this would likely have to be revisited anyway.
  image

Exit status 65: no relevant streams after filter:
-  HUC 04280001:  Located in the northern part of lake Ontario, most of this HUC8 is within the outer lake boundary; There is a mismatch between NWM stream segments and NHDPlus HR segments in this area. (I have manually removed this HUC from the FR list)
  image
  Where the green lines are NHDPlus HR and the blue lines are NWM. Maybe this area is still under revision. I have removed this layer from the FR HUC list `included_huc8.lst`. 

- HUC 10170104:  no NHDPlus HR data for this HUC8 (I have manually removed this HUC from the FR list)

## Evaluation

No change was observed in MS aggregate CSI scores

USGS
image

NWS
image

BLE
image

### CODE REVIEW

**Comment by BradfordBates-NOAA** [comment]
@BrianAvant-NOAA Do you have recommended steps for testing? I was going to run `fim_run.sh` on some of the known bad HUCs to ensure that the error handling is operating as designed. Can you think of anything else?

**Comment by BrianAvant-NOAA** [comment]
@nickchadwick-noaa @BradfordBates-NOAA Using the 2 hour timeout on `run_by_unit.sh` resulted in 51 FR HUC8 jobs getting killed before they finished: `01050002,04050001,04140201,04160003,04200008,04210004,04220001,04220002,04320000,05060001,05100101,08020203,09030001,09030003,10030101,10040104,10040201,10100001,10100004,10110101,10110201,10120202,10130102,10130105,10130306,10140101,10140102,10140201,10160003,10170203,10180009,10200101,10300102,13030202,13050003,13050004,13080002,14080106,15010013,15030104,15070201,15080200,16060001,16060007,16060008,16060011,16060012,16060014,17010101,17020001,17020006`. Some of these may be related to issues handling incoming streams around the Great lakes but I think others are just really large HUCs. We probably relax that time limit or maybe even remove it altogether.

**Comment by BradfordBates-NOAA** [comment]
I'm running FR again with the timeout removed.

**Comment by BradfordBates-NOAA** [comment]
I reran all of the failed HUCs on the dev VM, and all but one finished successfully (1305004: Exit status 137), this is likely a memory issue. So it would appear that the timeout was responsible for the failed HUCs in the previous run.

**Review by BradfordBates-NOAA — APPROVED** [review]
After removing the timeout and testing on the dev VM, the failed HUCs completed without error.

**Pull request merged**
